export default {
  "plus": 3,
  "comme": 5,
  "premier": 4,
  "bien": 1,
  "groupe": 5,
  "sans": 3,
  "fin": 1,
  "non": 2,
  "notamment": 4,
  "grand": 4,
  "grande ": 3 ,
  "nouveau": 1,
  "nouvelle": 5,
  "toujours": 3,
  "exemple": 5,
  "droit": 4,
  "travail": 5,
  "succès": 3,
  "joueur": 2,
  "grâce": 2,
  "création": 5,
  "gend": 2,
  "prix": 1,
  "rapport": 4,
  "haut": 4,
  "possible": 3,
  "important": 4,
  "assez": 1,
  "nouvelles": 3,
  "propd": 2,
  "victoid": 2,
  "importante ": 5,
  "principal": 2,
  "rapidement": 3,
  "marque ": 3,
  "droite ": 5,
  "œuvd": 2,
  "simple": 5,
  "dessus": 3,
  "right": 4,
  "capitale": 5,
  "personnage ": 2,
  "nouveaux": 1,
  "classe ": 4,
  "meilleur": 2,
  "source": 2,
  "libd": 2,
  "bon": 2,
  "économique ": 3,
  "célèbd": 2,
  "populaid": 2,
  "valeur": 2,
  "bonne": 5,
  "pratique ": 3,
  "large ": 2,
  "mieux": 2,
  "champion": 5,
  "marché": 1,
  "personnages": 3,
  "forte ": 5,
  "supérieur": 2,
  "saint": 4,
  "maîtd": 2,
  "classique ": 3,
  "juste ": 5,
  "courant": 4,
  "fond": 2,
  "protection": 5,
  "sécurité": 1,
  "d'or": 1,
  "feu": 1,
  "moderne": 5,
  "ami": 1,
  "supérieud": 2,
  "Premier": 4,
  "véritable": 3,
  "permis": 3,
  "soutien": 1,
  "largement": 3,
  "permettd": 2,
  "sommet": 4,
  "champ": 1,
  "paix": 1,
  "défaite ": 5,
  "capacité": 1,
  "liberté": 1,
  "offd": 2,
  "nouvel": 5,
  "vite ": 5,
  "conduit": 4,
  "traitement": 4,
  "naturel": 5,
  "laisse ": 4,
  "faveur": 2,
  "médaille": 5,
  "rapide ": 3 ,
  "travailler": 4,
  "top": 1,
  "sauf": 1,
  "caractéristiques": 3,
  "justice": 2,
  "jeunesse ": 4,
  "héros": 3,
  "riche": 5,
  "endémique ": 3,
  "réaliser": 3,
  "fête ": 5,
  "réalisation": 5,
  "accord": 4,
  "belle": 5,
  "humaine": 5,
  "profit": 4,
  "ferme": 5,
  "reconnu": 1,
  "gagne": 5,
  "massif": 1,
  "décidé": 1,
  "comprendd": 2,
  "disponible": 3,
  "protéger": 5,
  "beau": 1,
  "autonome": 5,
  "réforme": 5,
  "immédiatement": 4,
  "piste ": 5,
  "facilement": 3,
  "unité": 1,
  "influence": 2,
  "capable": 3,
  "hommage ": 2,
  "vainqueur": 2,
  "ciel": 5,
  "sûr": 1,
  "répondd": 2,
  "merci": 1,
  "inspiré": 1,
  "précise ": 4,
  "puits": 3,
  "royal": 2,
  "direct": 4,
  "humain": 1,
  "complet": 4,
  "pleine": 5,
  "travaillé": 1,
  "libération": 5,
  "disposition": 5,
  "assud": 2,
  "pêche": 5,
  "foi": 1,
  "précisément": 4,
  "importance": 2,
  "intègd": 2,
  "clair": 2,
  "dirigeants": 3,
  "gagner": 5,
  "affluent": 4,
  "or": 1,
  "recevoir": 2,
  "destinée": 2,
  "défendd": 2,
  "renommée": 2,
  "réputation": 5,
  "tenir": 2,
  "respect": 4,
  "réussi": 1,
  "succède ": 3 ,
  "clairement": 4,
  "estime": 5,
  "extrêmement": 4,
  "confiance": 2,
  "goût": 4,
  "améliorer": 5,
  "maintenir": 2,
  "logique ": 3,
  "révolutionnaid": 2,
  "puissant": 4,
  "assurer": 5,
  "utile": 5,
  "conseils": 3,
  "sportif": 1,
  "frais": 3,
  "augmentation": 5,
  "aider": 5,
  "riches": 3,
  "facile": 5,
  "relève": 5,
  "adapté": 1,
  "accessible": 3,
  "efficace": 2,
  "maîtrise ": 4,
  "gagné": 1,
  "intérêts": 3,
  "support": 4,
  "défenseur": 2,
  "soutenu": 1,
  "suffisamment": 4,
  "remarquable": 3,
  "chance": 2,
  "relief": 1,
  "soutient": 4,
  "affaid": 2,
  "avocat": 4,
  "suffit": 4,
  "mener": 5,
  "secours": 3,
  "favorable": 3,
  "compétences": 3,
  "franchise ": 4,
  "maîtres": 3,
  "parfaitement": 4,
  "prêt": 4,
  "recours": 3,
  "capital": 2,
  "regard": 4,
  "soutenir": 2,
  "nourritud": 2,
  "bons": 3,
  "précis": 3,
  "intégré": 1,
  "contribution": 5,
  "l'unité": 1,
  "définir": 2,
  "talent": 4,
  "suprême": 5,
  "distinction": 5,
  "fortune": 5,
  "progrès": 3,
  "génie": 5,
  "rose ": 4,
  "défaites": 3,
  "accueillir": 2,
  "chaleur": 2,
  "fameux": 2,
  "solide ": 3 ,
  "promouvoir": 2,
  "sainte ": 5,
  "amour": 4,
  "noble": 5,
  "passion": 5,
  "amoureux": 2,
  "considérer": 5,
  "trophée": 2,
  "dynamique ": 3,
  "fidèle": 5,
  "richesse ": 4,
  "fans": 3,
  "profondément": 4,
  "récupérer": 5,
  "préparer": 5,
  "autorité": 1,
  "traiter": 5,
  "qualifié": 1,
  "plaisir": 2,
  "beauté": 1,
  "fonctionne": 5,
  "récompense ": 4,
  "renommé": 1,
  "libéré": 1,
  "préfèd": 2,
  "faciliter": 5,
  "sacré": 1,
  "modeste ": 5,
  "profonde ": 3 ,
  "alliance": 2,
  "équivalent": 4,
  "économie": 5,
  "réformes": 3,
  "respecter": 5,
  "durable": 3,
  "sensible": 3,
  "proprement": 4,
  "dépasse ": 4,
  "diriger": 5,
  "pro": 1,
  "renforcer": 5,
  "mine": 5,
  "progression": 5,
  "douce": 2,
  "domine": 5,
  "immense ": 4,
  "corriger": 5,
  "compléter": 5,
  "augmenter": 5,
  "assuré": 1,
  "vertu": 1,
  "gloid": 2,
  "ouvertud": 2,
  "intéressant": 4,
  "convaincd": 2,
  "conduid": 2,
  "honneur": 2,
  "grandeur": 2,
  "patients": 3,
  "animé": 1,
  "prête ": 5,
  "chaud": 4,
  "talents": 3,
  "profond": 4,
  "permanent": 4,
  "engagement": 3,
  "confirmé": 1,
  "aime": 5,
  "positif": 1,
  "libérer": 5,
  "courante ": 5,
  "stable": 3,
  "favoriser": 3,
  "volontaid": 2,
  "ordonné": 1,
  "aidé": 1,
  "claid": 2,
  "régulier": 4,
  "notable": 3,
  "courage ": 2,
  "qualifier": 4,
  "autorisé": 1,
  "championne": 5,
  "calme": 5,
  "rayonnement": 4,
  "adresse ": 4,
  "allié": 1,
  "qualifiés": 3,
  "bonheur": 2,
  "mérite ": 5,
  "ben": 1,
  "stabilité": 1,
  "patient": 4,
  "prestigieux": 2,
  "fleur": 2,
  "parfait": 4,
  "pur": 4,
  "continuité": 1,
  "plomb": 1,
  "repos": 3,
  "doux": 1,
  "destin": 1,
  "avantage ": 2,
  "pud": 2,
  "luxe": 5,
  "magie": 5,
  "pic": 1,
  "prouver": 5,
  "réalisations": 3,
  "avantages": 3,
  "illustd": 2,
  "offrir": 2,
  "crédit": 4,
  "apprécié": 1,
  "justement": 4,
  "diplomatique ": 3,
  "bonus": 3,
  "profiter": 5,
  "fantastique ": 3,
  "sonde ": 3 ,
  "librement": 4,
  "fine": 5,
  "renseignements": 3,
  "poétique ": 3,
  "triomphe": 5,
  "gagnant": 4,
  "survie": 5,
  "correctement": 4,
  "dépasser": 3,
  "précieux": 2,
  "spirituel": 5,
  "préféré": 1,
  "magique ": 3,
  "net": 4,
  "vive": 5,
  "fonctionner": 5,
  "heureux": 2,
  "salut": 4,
  "extraordinaid": 2,
  "positive": 5,
  "restaurer": 5,
  "décerné": 1,
  "romantique ": 3,
  "joie": 5,
  "idéal": 2,
  "invite ": 5,
  "maturité": 1,
  "vif": 1,
  "restauré": 1,
  "légal": 2,
  "légendaid": 2,
  "libertés": 3,
  "suffisante ": 5,
  "animée": 2,
  "gain": 1,
  "exemplaid": 2,
  "prestige ": 2,
  "spirituelle": 5,
  "légitime": 5,
  "prospérité": 1,
  "avancée": 2,
  "bénéfice": 2,
  "portion": 5,
  "vaincu": 1,
  "récompenses": 3,
  "solidarité": 1,
  "exceptionnel": 5,
  "excellent": 4,
  "défenseurs": 3,
  "dominé": 1,
  "préférence": 2,
  "prime": 5,
  "traction": 5,
  "renouveau": 1,
  "assurant": 4,
  "complément": 4,
  "magnifique ": 3,
  "conforme": 5,
  "rapprochement": 4,
  "significative": 5,
  "déterminé": 1,
  "obtenus": 3,
  "gratuit": 4,
  "renaissance": 2,
  "confier": 4,
  "résistant": 4,
  "recommandations": 3,
  "avancé": 1,
  "brillant": 4,
  "appeler": 4,
  "porteur": 2,
  "sérieusement": 3,
  "décisive": 5,
  "fidélité": 1,
  "progressive": 5,
  "entraînant": 4,
  "Marvel": 5,
  "vaincd": 2,
  "pousser": 3,
  "gratuitement": 4,
  "énergétique ": 3,
  "accueil": 5,
  "divine": 5,
  "bétail": 5,
  "dignité": 1,
  "rachat": 4,
  "progressif": 1,
  "sensiblement": 3,
  "facilité": 1,
  "combattant": 4,
  "nourrir": 2,
  "passionné": 1,
  "sage ": 2,
  "garantir": 2,
  "négocier": 4,
  "satisfaid": 2,
  "célébrer": 5,
  "équilibd": 2,
  "progressiste ": 5,
  "attribuer": 5,
  "protecteur": 2,
  "charme": 5,
  "ouvertement": 4,
  "attirer": 5,
  "réaliste ": 5,
  "complémentaid": 2,
  "l'amélioration": 5,
  "énormément": 4,
  "succéder": 5,
  "spectaculaid": 2,
  "garantie": 5,
  "équipement": 4,
  "doré": 1,
  "réussir": 2,
  "orientation": 5,
  "révélation": 5,
  "exact": 4,
  "compatible": 3,
  "lucratif": 1,
  "promesse ": 4,
  "lumineux": 2,
  "digne": 5,
  "déterminée": 2,
  "favori": 1,
  "naîtd": 2,
  "percée": 2,
  "supports": 3,
  "abondante ": 5,
  "savant": 4,
  "crème": 5,
  "cohérence": 2,
  "marcher": 5,
  "efficacité": 1,
  "prouve": 5,
  "chaude ": 3 ,
  "divin": 1,
  "excellente ": 5,
  "décisif": 1,
  "lyrique ": 3,
  "conquérir": 2,
  "privilège ": 2,
  "nette ": 5,
  "confort": 4,
  "amical": 2,
  "constant": 4,
  "intime": 5,
  "sagesse ": 4,
  "supériorité": 1,
  "approuvé": 1,
  "recommandé": 1,
  "sensation": 5,
  "effective": 5,
  "recommandation": 5,
  "fiable": 3,
  "privilégié": 1,
  "amélioration": 5,
  "ordonnance": 2,
  "prédilection": 5,
  "améliorations": 3,
  "promis": 3,
  "ressource": 2,
  "renformement": 3,
  "tolérance": 2,
  "hospitalier": 4,
  "Hardy": 1,
  "foid": 2,
  "aimé": 1,
  "intelligence": 2,
  "accompli": 1,
  "intégrante ": 5,
  "agréable": 3,
  "promet": 4,
  "pacifique ": 3,
  "fiabilité": 1,
  "céleste ": 5,
  "célébration": 5,
  "cultivé": 1,
  "brise ": 4,
  "humoristique ": 3,
  "lumières": 3,
  "paradis": 3,
  "positifs": 3,
  "rétablissement": 3,
  "satisfait": 4,
  "correct": 4,
  "significatif": 1,
  "volontiers": 3,
  "pile": 5,
  "cud": 2,
  "ambitieux": 2,
  "vivement": 2,
  "relancer": 5,
  "célébré": 1,
  "amélioré": 1,
  "intégrale": 5,
  "alliée": 2,
  "prospèd": 2,
  "amener": 5,
  "encourage ": 2,
  "préférant": 4,
  "coopérative": 5,
  "master": 5,
  "théologien": 1,
  "tentant": 4,
  "décidée": 2,
  "humour": 4,
  "analogue ": 3,
  "préférable": 3,
  "complétée": 2,
  "améliorée": 2,
  "admissible": 3,
  "accomplir": 2,
  "reconnaissant": 4,
  "améliod": 2,
  "progresser": 3,
  "veine": 5,
  "dégager": 5,
  "amant": 4,
  "efficamement": 3,
  "plaît": 4,
  "croyant": 4,
  "divertissement": 3,
  "renom": 1,
  "positives": 3,
  "contente ": 5,
  "authentique ": 3,
  "gains": 3,
  "portable": 3,
  "miracle": 5,
  "superbe": 5,
  "affirmer": 5,
  "mince": 2,
  "coffd": 2,
  "approprié": 1,
  "excellence": 2,
  "patriotique ": 3,
  "prolifique ": 3,
  "résolu": 1,
  "discret": 4,
  "vœu": 1,
  "distingué": 1,
  "sympathie": 5,
  "attraction": 5,
  "pardon": 2,
  "restructuration": 5,
  "best": 4,
  "influent": 4,
  "élite ": 5,
  "raisonnable": 3,
  "éthique ": 3,
  "réconciliation": 5,
  "compact": 4,
  "renouvelé": 1,
  "inspiration": 5,
  "accueillant": 4,
  "bravoud": 2,
  "Passion": 5,
  "souple": 5,
  "favorisé": 1,
  "propice": 2,
  "guérison": 2,
  "victorieux": 2,
  "économies": 3,
  "facilite ": 5,
  "intelligent": 4,
  "d'élite ": 5,
  "nouveauté": 1,
  "commander": 5,
  "promoteur": 2,
  "fermement": 4,
  "floraison": 2,
  "doué": 1,
  "récompenser": 3,
  "ambition": 5,
  "apprécie": 5,
  "honorable": 3,
  "désireux": 2,
  "heureuse ": 4,
  "légalement": 3,
  "indigène": 5,
  "simplifié": 1,
  "affectée": 2,
  "trompette ": 5,
  "tranquille": 5,
  "amende ": 3 ,
  "exigeant": 4,
  "cohésion": 5,
  "lisse ": 4,
  "alcoolique ": 3,
  "fertile": 5,
  "veuillez": 1,
  "jolie": 5,
  "impressionnant": 4,
  "honoré": 1,
  "survivant": 4,
  "racheter": 5,
  "organisateur": 2,
  "perfection": 5,
  "bénédiction": 5,
  "écurie": 5,
  "free": 5,
  "soigneusement": 3,
  "enthousiasme": 5,
  "vivace": 2,
  "élever": 5,
  "consommer": 5,
  "consommé": 1,
  "innovation": 5,
  "suprématie": 5,
  "réformée": 2,
  "goûts": 3,
  "fair": 2,
  "impressionnante ": 5,
  "harmonie": 5,
  "nappe": 5,
  "loyauté": 1,
  "dynamisme": 5,
  "encourager": 5,
  "utilisable": 3,
  "héroïque ": 3,
  "formidable": 3,
  "guérir": 2,
  "chauffeur": 2,
  "admirer": 5,
  "finesse ": 4,
  "étonnant": 4,
  "content": 4,
  "fêter": 5,
  "résolument": 4,
  "talentueux": 2,
  "fier": 4,
  "merveilleux": 2,
  "miracles": 3,
  "soudain": 1,
  "prudence": 2,
  "l'assurance": 2,
  "simplifier": 4,
  "cohérent": 4,
  "sourid": 2,
  "robuste ": 5,
  "douceur": 2,
  "richement": 4,
  "affirmation": 5,
  "apprécier": 4,
  "impressionné": 1,
  "habile": 5,
  "informer": 5,
  "remédier": 4,
  "pareil": 5,
  "estimer": 5,
  "clarté": 1,
  "rationnelle": 5,
  "frappant": 4,
  "dominer": 5,
  "consistent": 4,
  "délicat": 4,
  "pittoresque ": 3,
  "ange ": 2,
  "érudit": 4,
  "inspid": 2,
  "confortable": 3,
  "heureusement": 3,
  "nettoyer": 5,
  "intégral": 2,
  "motivé": 1,
  "affection": 5,
  "favorite ": 5,
  "protagoniste ": 5,
  "calmer": 5,
  "guider": 5,
  "panoramique ": 3,
  "piété": 1,
  "spontanée": 2,
  "remercier": 4,
  "abondant": 4,
  "exhaustif": 1,
  "fierté": 1,
  "troupeau": 1,
  "généreux": 2,
  "équitable": 3,
  "simplifiée": 2,
  "paisible": 3,
  "sensations": 3,
  "joli": 1,
  "aristocratique ": 3,
  "approuve": 5,
  "accroîtd": 2,
  "optimale": 5,
  "polyvalent": 4,
  "souplesse ": 4,
  "stabiliser": 3,
  "générosité": 1,
  "fervent": 4,
  "originalité": 1,
  "gentil": 5,
  "surréaliste ": 5,
  "primordial": 2,
  "transparent": 4,
  "perche": 5,
  "navigable": 3,
  "sympathique ": 3,
  "admiration": 5,
  "honorer": 5,
  "coloré": 1,
  "privilégier": 4,
  "aristocrate ": 5,
  "réformer": 5,
  "courageux": 2,
  "bienvenue ": 3,
  "cohérente ": 5,
  "éminent": 4,
  "finement": 4,
  "aimer": 5,
  "éternel": 5,
  "subvention": 5,
  "concilier": 4,
  "love": 5,
  "éclat": 4,
  "assurances": 3,
  "enrichir": 2,
  "abondance": 2,
  "instrumental": 2,
  "réformé": 1,
  "patience": 2,
  "assurance": 2,
  "louer": 5,
  "souhaitable": 3,
  "serré": 1,
  "enthousiaste ": 5,
  "désirant": 4,
  "caractériser": 3,
  "brillants": 3,
  "rembourser": 3,
  "vigilance": 2,
  "élégant": 4,
  "dégagé": 1,
  "merveilles": 3,
  "honnête ": 5,
  "achever": 5,
  "promise ": 4,
  "stabilisation": 5,
  "atout": 4,
  "silencieux": 2,
  "sain": 1,
  "satisfaisante ": 5,
  "satisfaisant": 4,
  "flottant": 4,
  "soigné": 1,
  "chevalerie": 5,
  "joyeux": 2,
  "fraîche": 5,
  "bénéfique ": 3,
  "rationnel": 5,
  "aspirations": 3,
  "ordonnée": 2,
  "compacte ": 5,
  "pencher": 5,
  "ranger": 5,
  "héroïne": 5,
  "ardent": 4,
  "attirant": 4,
  "dépassement": 3,
  "patriote ": 5,
  "doumement": 3,
  "intelligente ": 5,
  "soulager": 5,
  "amicalement": 3,
  "compréhensible": 3,
  "tuyau": 1,
  "réconcilier": 4,
  "lisible": 3,
  "farouche": 5,
  "remède ": 3 ,
  "prometteur": 2,
  "crédible": 3,
  "perfectionnement": 4,
  "préférer": 5,
  "like": 5,
  "primordiale": 5,
  "décerner": 5,
  "retentissement": 3,
  "diversifiée": 2,
  "gagnants": 3,
  "jeûne": 5,
  "idole": 5,
  "aromatique ": 3,
  "rosé": 1,
  "luxueux": 2,
  "admirateur": 2,
  "fidèlement": 3,
  "judicieux": 2,
  "élastique ": 3,
  "mémorable": 3,
  "faste ": 5,
  "confiant": 4,
  "attentif": 1,
  "perfectionner": 5,
  "solidité": 1,
  "l'inspiration": 5,
  "débiteur": 2,
  "tranquillité": 1,
  "animer": 5,
  "futuriste ": 5,
  "jouir": 2,
  "coupant": 4,
  "novateur": 2,
  "stimuler": 4,
  "guidé": 1,
  "charismatique ": 3,
  "glorieux": 2,
  "boom": 1,
  "prouvant": 4,
  "trompettiste ": 5,
  "Swift": 4,
  "stellaid": 2,
  "bénéficiaid": 2,
  "ludique ": 3,
  "velours": 3,
  "habileté": 1,
  "majesté": 1,
  "ferveur": 2,
  "uniformément": 4,
  "amicale": 5,
  "penchant": 4,
  "grêle": 5,
  "solidement": 3,
  "indiscutable": 3,
  "incontestable": 3,
  "sincèd": 2,
  "scénique ": 3,
  "bienfaisance": 2,
  "motivée": 2,
  "admid": 2,
  "bonté": 1,
  "pêcher": 5,
  "saine": 5,
  "éclairer": 5,
  "équilibré": 1,
  "positivement": 2,
  "adod": 2,
  "juvénile": 5,
  "splendeur": 2,
  "transparente ": 5,
  "merveille": 5,
  "sympa": 1,
  "deviner": 5,
  "somptueux": 2,
  "pointu": 1,
  "réussissant": 4,
  "convenable": 3,
  "parfaid": 2,
  "créatif": 1,
  "taid": 2,
  "bol": 5,
  "prometteurs": 3,
  "aimant": 4,
  "couronner": 5,
  "bienveillance": 2,
  "adéquate ": 5,
  "tranchant": 4,
  "fanfad": 2,
  "fascination": 5,
  "étonné": 1,
  "respectueux": 2,
  "tranquillement": 3,
  "autoriser": 3,
  "véracité": 1,
  "plaid": 2,
  "prédid": 2,
  "couvercle": 5,
  "moralité": 1,
  "adéquat": 4,
  "productif": 1,
  "grâces": 3,
  "oasis": 3,
  "résolue ": 3,
  "réfléchi": 1,
  "chauffer": 5,
  "sélectif": 1,
  "bienheureux": 2,
  "sucré": 1,
  "viable": 3,
  "diversifié": 1,
  "remarquablement": 3,
  "redresser": 3,
  "réflexe": 5,
  "approbation": 5,
  "clarifier": 4,
  "vérifiable": 3,
  "solid": 4,
  "hein": 1,
  "félicitations": 3,
  "encourageant": 4,
  "influente ": 5,
  "brillamment": 4,
  "jouissance": 2,
  "fabuleux": 2,
  "brave": 5,
  "compléments": 3,
  "dévoué": 1,
  "flexibilité": 1,
  "flottante ": 5,
  "flexible": 3,
  "ample": 5,
  "charisme": 5,
  "prodige ": 2,
  "molle": 5,
  "joyeuse ": 4,
  "amusant": 4,
  "instruit": 4,
  "percées": 3,
  "créative": 5,
  "splendide ": 3 ,
  "miraculeuse ": 4,
  "avantageux": 2,
  "constructive": 5,
  "respectable": 3,
  "politesse ": 4,
  "ménager": 5,
  "informés": 3,
  "commode ": 3 ,
  "cool": 5,
  "idéalement": 3,
  "sincérité": 1,
  "garant": 4,
  "incontestablement": 3,
  "coopératif": 1,
  "substantif": 1,
  "loyal": 2,
  "sexy": 1,
  "rassurer": 5,
  "auspices": 3,
  "distinctif": 1,
  "fructueuse ": 4,
  "saluer": 5,
  "balayage ": 2,
  "grandiose ": 4,
  "sérénité": 1,
  "aspid": 2,
  "sublime": 5,
  "habilement": 3,
  "acclamé": 1,
  "charmant": 4,
  "excelle": 5,
  "inspirer": 5,
  "aimable": 3,
  "s'approprier": 4,
  "poli": 1,
  "optimal": 2,
  "élégance": 2,
  "miraculeusement": 3,
  "articulé": 1,
  "optimiste ": 5,
  "raffiné": 1,
  "productive": 5,
  "généreuse ": 4,
  "chouette ": 5,
  "éprouvé": 1,
  "rédemption": 5,
  "affinité": 1,
  "avocate ": 5,
  "fun": 1,
  "suffid": 2,
  "aisance": 2,
  "mûr": 1,
  "plaider": 5,
  "intuitive": 5,
  "attirance": 2,
  "saillant": 4,
  "retentissant": 4,
  "sincèrement": 4,
  "répit": 4,
  "motivés": 3,
  "enlèvement": 2,
  "apaiser": 3,
  "briller": 4,
  "raffinement": 4,
  "prospérer": 5,
  "matud": 2,
  "spontané": 1,
  "approuver": 5,
  "courtois": 3,
  "chaleureux": 2,
  "radioactif": 1,
  "appréciable": 3,
  "triompher": 5,
  "patiente ": 5,
  "diligence": 2,
  "opportun": 1,
  "modestie": 5,
  "innovante ": 5,
  "avanmement": 3,
  "attentive": 5,
  "épris": 3,
  "tenace": 2,
  "raisonnablement": 3,
  "work": 1,
  "admirable": 3,
  "visionnaid": 2,
  "providence": 2,
  "compétitif": 1,
  "harmonieux": 2,
  "feat": 4,
  "soulagement": 3,
  "ardeur": 2,
  "bienfaiteur": 2,
  "miséricorde ": 3 ,
  "rectifier": 4,
  "affluence": 2,
  "propreté": 1,
  "gentillesse ": 4,
  "illimité": 1,
  "efface": 2,
  "obsession": 5,
  "constructif": 1,
  "simplifie": 5,
  "amplement": 3,
  "embrasser": 3,
  "puissamment": 4,
  "attractif": 1,
  "bienvenu": 1,
  "ravi": 1,
  "Glee": 5,
  "personnalisé": 1,
  "impressionne": 5,
  "recouvrer": 5,
  "triomphal": 2,
  "séduisant": 4,
  "profusion": 5,
  "sauveur": 2,
  "félicité": 1,
  "florissant": 4,
  "amorcé": 1,
  "masters": 3,
  "raisonner": 5,
  "chevaleresque ": 3,
  "étonnamment": 4,
  "inoxydable": 3,
  "agile": 5,
  "convaincante ": 5,
  "sophistiqué": 1,
  "incontesté": 1,
  "stimule": 5,
  "persévérance": 2,
  "purifier": 4,
  "prouesses": 3,
  "cime": 5,
  "joyau": 1,
  "engageant": 4,
  "festive": 5,
  "personnaliser": 3,
  "réalisable": 3,
  "épargne": 5,
  "triomphale": 5,
  "louange ": 2,
  "consolation": 5,
  "délicatesse ": 4,
  "vertueux": 2,
  "promettd": 2,
  "polie": 5,
  "chic": 1,
  "séduisante ": 5,
  "majestueux": 2,
  "excité": 1,
  "prévoyance": 2,
  "lustd": 2,
  "agrément": 4,
  "gratitude ": 3 ,
  "étonnement": 4,
  "rangé": 1,
  "copine": 5,
  "ténacité": 1,
  "sentimental": 2,
  "préconisé": 1,
  "commodité": 1,
  "jouissant": 4,
  "stimulant": 4,
  "oh": 1,
  "soft": 4,
  "motiver": 5,
  "féliciter": 5,
  "satisfaite ": 5,
  "réconfort": 4,
  "mériter": 5,
  "intacts": 3,
  "duvet": 4,
  "confident": 4,
  "lucide ": 3 ,
  "excéder": 5,
  "gentiment": 4,
  "irréprochable": 3,
  "enrichissement": 3,
  "welcome": 5,
  "gracieux": 2,
  "fleurir": 2,
  "grace": 2,
  "convivialité": 1,
  "peluche": 5,
  "convaincant": 4,
  "stylisé": 1,
  "good": 4,
  "charitable": 3,
  "chanceux": 2,
  "recommander": 5,
  "divertir": 2,
  "minutieusement": 3,
  "rectification": 5,
  "amovible": 3,
  "rescapé": 1,
  "fortuite ": 5,
  "transe ": 4,
  "fast": 4,
  "abordable": 3,
  "ingénieux": 2,
  "hot": 4,
  "aspiration": 5,
  "éloquence": 2,
  "triomphant": 4,
  "bienveillant": 4,
  "irrésistible": 3,
  "invincible": 3,
  "dièse ": 4,
  "enchanté": 1,
  "pacifiquement": 4,
  "durabilité": 1,
  "éclatant": 4,
  "réglable": 3,
  "éprouvée": 2,
  "attractive": 5,
  "chaleureusement": 3,
  "ventilateur": 2,
  "gentille": 5,
  "excitation": 5,
  "intimité": 1,
  "battement": 4,
  "gai": 1,
  "souriant": 4,
  "plaisant": 4,
  "attachant": 4,
  "ardemment": 4,
  "serrer": 5,
  "agilité": 1,
  "réchauffer": 5,
  "lucrative": 5,
  "éclaircir": 2,
  "affiner": 5,
  "survivante ": 5,
  "piquant": 4,
  "pros": 3,
  "affectueux": 2,
  "mignon": 2,
  "intuitif": 1,
  "fructueux": 2,
  "toupie": 5,
  "patiemment": 4,
  "adoré": 1,
  "idol": 5,
  "généreusement": 3,
  "frappante ": 5,
  "branché": 1,
  "mûd": 2,
  "gemme": 5,
  "amusante ": 5,
  "faisable": 3,
  "éminence": 2,
  "bienveillante ": 5,
  "triomphalement": 3,
  "présage ": 2,
  "trouée": 2,
  "substantiel": 5,
  "âpd": 2,
  "impressionner": 5,
  "surpasser": 3,
  "inestimable": 3,
  "zénith": 1,
  "consoler": 4,
  "trust": 4,
  "lead": 4,
  "gemmes": 3,
  "spacieux": 2,
  "portatif": 1,
  "prouesse ": 4,
  "fulgurant": 4,
  "honnêteté": 1,
  "Jolly": 1,
  "étable": 3,
  "vigilant": 4,
  "révolutionné": 1,
  "prodigieux": 2,
  "augud": 2,
  "défricher": 5,
  "distinctive": 5,
  "inoffensif": 1,
  "prompt": 4,
  "award": 4,
  "enflammé": 1,
  "passionnant": 4,
  "humilité": 1,
  "affectueusement": 3,
  "réaffirmer": 5,
  "serein": 1,
  "rémission": 5,
  "chaleureuse ": 4,
  "éclairant": 4,
  "miraculeux": 2,
  "harmonieusement": 3,
  "endetté": 1,
  "éduqués": 3,
  "vaillamment": 4,
  "délicieux": 2,
  "subventionné": 1,
  "phénoménal": 2,
  "maniable": 3,
  "entrain": 1,
  "évocateur": 2,
  "restructuré": 1,
  "attester": 5,
  "remboursé": 1,
  "intelligible": 3,
  "confortablement": 3,
  "fécond": 4,
  "équitablement": 3,
  "luxuriante ": 5,
  "rationaliser": 3,
  "harmoniser": 3,
  "magnifiquement": 4,
  "courageusement": 3,
  "experte ": 5,
  "vaillance": 2,
  "stupéfaction": 5,
  "sociable": 3,
  "probant": 4,
  "méritant": 4,
  "audible": 3,
  "accomplissement": 3,
  "tender": 5,
  "ouah": 1,
  "amante ": 5,
  "affiné": 1,
  "rétractable": 3,
  "judicieusement": 3,
  "gaieté": 1,
  "oser": 3,
  "gracieusement": 3,
  "ravir": 2,
  "mordu": 1,
  "flatteur": 2,
  "rachis": 3,
  "droitud": 2,
  "bénir": 2,
  "s'épanouir": 2,
  "mousseux": 2,
  "vénérer": 5,
  "admirablement": 3,
  "sucreries": 3,
  "réjouissances": 3,
  "restructurer": 5,
  "inégalée": 2,
  "passionnément": 4,
  "ovation": 5,
  "licite ": 5,
  "conciliant": 4,
  "infaillible": 3,
  "vaillant": 4,
  "extraordinairement": 4,
  "embellir": 2,
  "abonde ": 3 ,
  "impeccable": 3,
  "inspirant": 4,
  "Trump": 1,
  "happy": 1,
  "agréablement": 3,
  "impartial": 2,
  "galant": 4,
  "entreprenant": 4,
  "bienheureuse ": 4,
  "éloquent": 4,
  "magnificence": 2,
  "gold": 4,
  "well": 5,
  "véridique ": 3,
  "idyllique ": 3,
  "mouvementé": 1,
  "révolutionner": 5,
  "fascinant": 4,
  "inébranlable": 3,
  "prévenant": 4,
  "gracieuse ": 4,
  "fougueux": 2,
  "rajeunir": 2,
  "rafraîchir": 2,
  "glamour": 4,
  "acclamation": 5,
  "savoureux": 2,
  "concis": 3,
  "enviable": 3,
  "aube": 5,
  "attrayant": 4,
  "parcimonie": 5,
  "concise ": 4,
  "révérence": 2,
  "parfumé": 1,
  "stupéfiant": 4,
  "désintéressé": 1,
  "clairvoyance": 2,
  "vibrante ": 5,
  "l'équité": 1,
  "aspirer": 5,
  "optimisme": 5,
  "inoubliable": 3,
  "sensé": 1,
  "indulgence": 2,
  "encouragement": 3,
  "réjouir": 2,
  "rassurant": 4,
  "mûrir": 2,
  "actionner": 5,
  "dévot": 4,
  "intrépide ": 3 ,
  "bonbon": 2,
  "cordiale": 5,
  "compliments": 3,
  "briquet": 4,
  "awards": 3,
  "prôner": 5,
  "chérie": 5,
  "great": 4,
  "angélique ": 3,
  "endosser": 3,
  "fraternel": 5,
  "smart": 4,
  "honorant": 4,
  "édifiant": 4,
  "héroïquement": 4,
  "inventif": 1,
  "chevronné": 1,
  "méritants": 3,
  "indubitablement": 3,
  "adaptable": 3,
  "sagacité": 1,
  "altruiste ": 5,
  "réconforter": 5,
  "luisant": 4,
  "promises": 3,
  "consciencieux": 2,
  "subventionner": 5,
  "joyeusement": 3,
  "hardi": 1,
  "amiable": 3,
  "envier": 4,
  "adroit": 4,
  "enflammée": 2,
  "confidence": 2,
  "golden": 1,
  "modern": 1,
  "glorifier": 4,
  "adorer": 5,
  "tonus": 3,
  "chaste ": 5,
  "mélodieux": 2,
  "gourmandise ": 4,
  "bosser": 3,
  "accolade ": 3 ,
  "solvabilité": 1,
  "sagement": 3,
  "lissage ": 2,
  "rayonnante ": 5,
  "ravis": 3,
  "louable": 3,
  "exquis": 3,
  "comprimer": 5,
  "prodiguer": 5,
  "revival": 2,
  "chéri": 1,
  "perspicacité": 1,
  "aventureux": 2,
  "amuse ": 4,
  "ready": 1,
  "méticuleusement": 3,
  "lucky": 1,
  "inoffensive": 5,
  "illumination": 5,
  "enjoué": 1,
  "braver": 5,
  "exciter": 5,
  "empressement": 3,
  "assainir": 2,
  "affranchir": 2,
  "admiratif": 1,
  "ingénieuse ": 4,
  "proéminent": 4,
  "obsessions": 3,
  "joliment": 4,
  "courtiser": 3,
  "better": 5,
  "revitaliser": 3,
  "costaud": 4,
  "exubérante ": 5,
  "persévérer": 5,
  "amuser": 3,
  "Gallant": 4,
  "érudite ": 5,
  "merveilleusement": 3,
  "lisser": 3,
  "extase ": 4,
  "excite ": 5,
  "impartialité": 1,
  "gratification": 5,
  "superbement": 4,
  "works": 3,
  "survival": 2,
  "frite ": 5,
  "classic": 1,
  "instructif": 1,
  "délicieuse ": 4,
  "désirable": 3,
  "réceptif": 1,
  "impartiale": 5,
  "assiduité": 1,
  "amender": 5,
  "affirmative": 5,
  "divertissant": 4,
  "won": 2,
  "individualisé": 1,
  "exalté": 1,
  "endettés": 3,
  "amusement": 3,
  "s'efforçant": 4,
  "épargnant": 4,
  "invulnérable": 3,
  "adorable": 3,
  "épicé": 1,
  "élégamment": 4,
  "rescapée": 2,
  "décence": 2,
  "flatter": 5,
  "disculper": 5,
  "clean": 1,
  "balayant": 4,
  "préconiser": 3,
  "justiciables": 3,
  "excitant": 4,
  "restructud": 2,
  "gem": 1,
  "frissons": 3,
  "décent": 4,
  "conciliante ": 5,
  "nettoyant": 4,
  "exubérant": 4,
  "sensationnel": 5,
  "irremplaçable": 3,
  "imagé": 1,
  "vigile": 5,
  "compliment": 4,
  "aubaine": 5,
  "jovial": 2,
  "adaptatif": 1,
  "transcender": 5,
  "poignant": 4,
  "détendu": 1,
  "adorée": 2,
  "suave": 5,
  "méticuleuse ": 4,
  "chaudement": 3,
  "sensitive": 5,
  "inoffensifs": 3,
  "empathie": 5,
  "copieux": 2,
  "peace": 2,
  "exaltation": 5,
  "méritoid": 2,
  "versatile": 5,
  "entériner": 5,
  "éblouissante ": 5,
  "savourer": 5,
  "chouchou": 1,
  "s'imaginer": 5,
  "indulgent": 4,
  "charmer": 5,
  "effilé": 1,
  "affable": 3,
  "tendrement": 4,
  "blockbuster": 5,
  "éloquente ": 5,
  "vigilants": 3,
  "accolades": 3,
  "ingéniosité": 1,
  "évocatrice": 2,
  "parfumer": 5,
  "preux": 2,
  "clear": 1,
  "odorant": 4,
  "galanterie": 5,
  "freedom": 1,
  "enchanteur": 2,
  "pressing": 1,
  "zeste ": 5,
  "somptueusement": 3,
  "poindd": 2,
  "cordial": 2,
  "articuler": 4,
  "martinet": 4,
  "fortuit": 4,
  "assouplissement": 3,
  "frisson": 2,
  "friandise ": 4,
  "applaudir": 2,
  "stimulants": 3,
  "protubérance": 2,
  "aurod": 2,
  "attentionné": 1,
  "stimulante ": 5,
  "civilité": 1,
  "harde ": 3 ,
  "available": 3,
  "smooth": 1,
  "prééminent": 4,
  "imaginatif": 1,
  "aimablement": 3,
  "sourires": 3,
  "proéminence": 2,
  "easy": 1,
  "jeûner": 5,
  "indolod": 2,
  "creative": 5,
  "bôme": 5,
  "serviable": 3,
  "gaiement": 4,
  "étonner": 5,
  "perspicace": 2,
  "nettoyeur": 2,
  "écoutez": 1,
  "perfect": 4,
  "inventive": 5,
  "exalter": 5,
  "béatitude ": 3 ,
  "sweet": 4,
  "rassurante ": 5,
  "Reved": 2,
  "magic": 1,
  "éblouissant": 4,
  "miséricordieux": 2,
  "impérieux": 2,
  "contentement": 4,
  "mignonne": 5,
  "tolérable": 3,
  "rafraîchissant": 4,
  "popular": 1,
  "lover": 5,
  "palatial": 2,
  "intrigant": 4,
  "immaculé": 1,
  "enough": 1,
  "beautiful": 5,
  "aiguiser": 3,
  "nanti": 1,
  "led": 4,
  "immaculée": 2,
  "débrouillard": 4,
  "intrigante ": 5,
  "imbattable": 3
}